version: "3"

services:
  web:
    build: .
    container_name: web
    ports:
      - "8004:8004"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boxbilling
      MYSQL_USER: boxbilling
      MYSQL_PASSWORD: password

volumes:
 mysql:
